### PR TITLE
Fix linting warnings

### PR DESCRIPTION
**Pull request by LinusU**
Was going to use this package so looked over the [score over att pub.dartland.org](https://pub.dartlang.org/packages/http#-analysis-tab-). The only things preventing a full 💯 score was these lint issues, which I've fixed in this PR.

Happy hacking 🍻

### CODE REVIEW

**Comment by kevmoo** [comment]
Please rebase on latest – to make sure we don't break backwards compat. Thanks much!

**Comment by LinusU** [comment]
> rebase on latest master

✅ 

> please enable the corresponding lints in `analysis_options.yaml`

@kevmoo do you want me to create this file? or am I just missing it 🤔

**Comment by LinusU** [comment]
@kevmoo I created the file and had it include `package:pedantic/analysis_options.yaml` which is what I think pub.dartlang.org uses 🚀

**Comment by LinusU** [comment]
Thanks! ❤️

**Comment by kevmoo** [comment]
Thank YOU! 👍

**Pull request merged**
