### PR TITLE
Fix null check exception in IOClient when sending http request (#581)

### PR DESCRIPTION
**Pull request by guyluz11**

### CODE REVIEW

**Comment by guyluz11** [comment]
@googlebot I signed it!

**Comment by kevmoo** [comment]
It seems like you have a case where you're trying to use the client after it's closed.

If anything, we should have a check in `send` that throws a clear error if `_inner` is `null`.

CC @natebosch

**Comment by guyluz11** [comment]
Should I open new clean pull request for it without this commit?

**Comment by kevmoo** [comment]
> Should I open new clean pull request for it without this commit?

That'd probably be best!

**Pull request closed without merging**
