### PR TITLE
Added the ability to retrieve `url` from `BaseResponse`

### PR DESCRIPTION
**Pull request by elmoiv**

### CODE REVIEW

**Comment by elmoiv** [comment]
@googlebot I signed it!

**Comment by kevmoo** [comment]
Add some documentation to the parameter and the field?

Why are you adding this? How does it help you?

**Comment by elmoiv** [comment]
It comes in handy when working with redirected urls. Like if I want to get the final retrieved URL after all redirects are done.

This adds the ability to get that from a `http.get` instead of the current workaround of setting `followRedirects` to false in `http.Request` or trying to check if response headers has the final url or not.

This was inspired from Python `requests` library

**Comment by elmoiv** [comment]
It appears that Dart CI Chrome tests are broken.

**Review by piotrsed — APPROVED** [review]

**Comment by natebosch** [comment]
If we are able to roll out this feature I think we'll use a `Uri` field instead of `String`. I'll pick this up in #699

**Pull request closed without merging**
