### PR TITLE
(BrowserClient) add constructor to set withCredentials value

### PR DESCRIPTION
**Pull request by AntoineDoubovetzky**
Hi,

I just added a constructor that takes an optional `withCredentials` value.

### CODE REVIEW

**Comment by AntoineDoubovetzky** [comment]
@googlebot I signed it!

**Comment by wolfpack94** [comment]
Any way this PR can get merged in? I would like this feature as well

**Comment by jamotaylor** [comment]
I don't see how this is going to help, because the only reference to the constructor call is this global function:

`BaseClient createClient() => BrowserClient();` ([lib/src/browser_client.dart - line 20](https://github.com/dart-lang/http/blob/a8efbef05a58919dc7aa2dab42198334f2459ffb/lib/src/browser_client.dart#L20))

So `withCredentials` will always have it's default value.

**Review by piotrsed — APPROVED** [review]

**Review by timleg002 — APPROVED** [review]

**Comment by mosuem** [comment]
Closing this, as it is stale and the files are out of date. Feel free to reopen in case you still want to land it!

**Pull request closed without merging**
