### PR TITLE
Fix for Content-Type issue support for Flutter Web.

### PR DESCRIPTION
**Pull request by seifibrahim32**
Hello @brianquinlan , kindly check the http_headers_utils folder, I added some new classes , and at exceptions.dart file for HttpException.

But I hadn't done for WebSockets yet as it needs to take some time to migrate from dart:io into the Http package.

### CODE REVIEW

**Review by brianquinlan — COMMENTED** [review]
Hi @seifibrahim32 

Thanks for your PR!

It doesn't make sense to add thousands of lines of code from dart:io just to get some constants into `package:http`.

If you are addressing #863 then I think that your goal should be to provide a convenient way  of extracting the content type from a response.

**Comment by seifibrahim32** [comment]
okay I will remove the HTTPParser and the non issue ....

**Comment by seifibrahim32** [comment]
@brianquinlan Check again with Flutter CI/CD please

**Comment by seifibrahim32** [comment]
Check CI/CD

**Comment by seifibrahim32** [comment]
@brianquinlan  Check CI/CD , I fixed the mini-issue for extra unused package :D

**Review by seifibrahim32 — COMMENTED** [review]
I assure that these changes are correct.

**Review by seifibrahim32 — COMMENTED** [review]
@brianquinlan

**Comment by seifibrahim32** [comment]
@brianquinlan  I fixed dart format issue from my local repo I synced the repo and merged it kindly re enable CI/CD please :D.

**Review by seifibrahim32 — COMMENTED** [review]
@brianquinlan

**Review by brianquinlan — COMMENTED** [review]
How is this meant to be used?

**Comment by seifibrahim32** [comment]
> How is this meant to be used?
Explain please

**Comment by seifibrahim32** [comment]
The CI/CD results show some issues for vm platform , but some unit mock tests for web shows it is supportive.
@brianquinlan

**Comment by brianquinlan** [comment]
> The CI/CD results show some issues for vm platform , but some unit mock tests for web shows it is supportive. @brianquinlan

I mean that you have a lot of functionality to represent headers but how should the user actually use it?

**Comment by seifibrahim32** [comment]
> > The CI/CD results show some issues for vm platform , but some unit mock tests for web shows it is supportive. @brianquinlan
> 
> I mean that you have a lot of functionality to represent headers but how should the user actually use it?

You mean the examples to return like the http default example because not necessarily to be used.

**Comment by seifibrahim32** [comment]
> > The CI/CD results show some issues for vm platform , but some unit mock tests for web shows it is supportive. @brianquinlan
> 
> I mean that you have a lot of functionality to represent headers but how should the user actually use it?

Or you need to remove the class which contains parse().

Show a file and let me change it

**Comment by seifibrahim32** [comment]
Mr Brian, you need to show an example how functional it would be used for the code? @brianquinlan

**Review by brianquinlan — COMMENTED** [review]
I think that you need to take a step back and think about what you are actually trying to achieve. 

The issue is asking for a convenient way of access `ContentType` (https://github.com/dart-lang/http/issues/863). We have not asked how exactly.

Using dart:io, you can write things like:

```dart
HttpClientRequest request = await client.get('localhost', 80, '/file.txt');
HttpClientResponse response = await request.close();
if (response.headers.contentType == ContentType.json) {
 ...
}
```

Are we trying to accomplish the equivalent for `package:http`? If so then you are missing the functionality to get the content type from the response directly.

But I'm not sure if that is what the issue is actually about - you'd need to ask what kind of API the developer is asking for.

**Comment by seifibrahim32** [comment]
@brianquinlan So we have to httpClientRequest and neighboring classes for endorsing web browsers in addition to HeaderValue and HttpHeaders class as previously it wasn't supporting web , this is the next approach ?

**Comment by brianquinlan** [comment]
> @brianquinlan So we have to httpClientRequest and neighboring classes for endorsing web browsers in addition to HeaderValue and HttpHeaders class as previously it wasn't supporting web , this is the next approach ?

I'm not suggesting an approach. I not sure if you are actually solving the user's problem.

**Comment by seifibrahim32** [comment]
> > @brianquinlan So we have to httpClientRequest and neighboring classes for endorsing web browsers in addition to HeaderValue and HttpHeaders class as previously it wasn't supporting web , this is the next approach ?
> 
> I'm not suggesting an approach. I not sure if you are actually solving the user's problem.

I mean the next step that we would add httpClientRequest for web as you teach me.

https://stackoverflow.com/questions/66339121/cant-post-from-flutter-web-with-httpclient

I found this issue on StackOverflow

I will try into that for sure.

**Pull request closed without merging**
