### PR TITLE
Fix a potential exponential backtracking issue when parsing quoted headers

### PR DESCRIPTION
**Pull request by brianquinlan**
Fixes https://github.com/dart-lang/http/issues/1433

@bkonyi Is there a way to verify that this fixes the issue with https://github.com/dart-lang/webdev/security/code-scanning/2 before landing this? Or I could land this but not publish until you can verify the fix.

---

- [X] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Review by natebosch — APPROVED** [review]

**Comment by bkonyi** [comment]
Thanks for the quick fix!

> @bkonyi Is there a way to verify that this fixes the issue with [Inefficient regular expression](/dart-lang/webdev/security/code-scanning/2) before landing this? Or I could land this but not publish until you can verify the fix.

I went ahead and pulled in this change through a path dependency and regenerated the `client.js` file. Let's see if that clears things up on https://github.com/dart-lang/webdev/pull/2546.

**Comment by bkonyi** [comment]
Yep, I think that fixed it!

**Comment by brianquinlan** [comment]
> Yep, I think that fixed it!

Thanks for testing this @bkonyi 

I'll land this now - do we need to do a release?

**Comment by bkonyi** [comment]
> > Yep, I think that fixed it!
> 
> Thanks for testing this @bkonyi
> 
> I'll land this now - do we need to do a release?

I don't think it's super urgent from my end, but it'd probably be good to release this sooner than later so the ecosystem can pick it up.

**Pull request merged**
