### PR TITLE
stable null safety release

### PR DESCRIPTION
**Pull request by jakemac53**

### CODE REVIEW

**Review by natebosch — APPROVED** [review]

**Comment by amantoux** [comment]
Unless I'm missing something, this cannot be used with Flutter beta
`Because http >=0.13.0 depends on path ^1.8.0 and every version of flutter_test from sdk depends on path 1.8.0-nullsafety.3, http >=0.13.0 is incompatible with flutter_test from sdk.`

**Comment by jakemac53** [comment]
flutter beta should have a cherry pick coming to update some deps to stable releases

**Comment by amantoux** [comment]
> flutter beta should have a cherry pick coming to update some deps to stable releases

Thanks!

**Comment by jhancock4d** [comment]
So is 0.13.0 the null safety release without the .nullsafety extension as is convention?

**Comment by jakemac53** [comment]
This is stable now so there is no pre-release suffix any longer. The `-nullsafety` extension is only for pre-releases.

**Comment by JohnGalt1717** [comment]
ok, thanks!

**Comment by jhancock4d** [comment]
Ok!

**Pull request merged**
