### PR TITLE
Fixes #295, multipart_request custom boundary

### LINKED ISSUE #295: Consider making multipart_request _boundaryString prefix configurable
One is unable to set a custom boundary value as it is hardcoded with "dart-http-boundary-".

### PR DESCRIPTION
**Pull request by DartMen**
Useful to exactly mimic web browsers #295.

### CODE REVIEW

**Comment by mit-mit** [comment]
Closing as CLA was not signed

**Comment by DartMen** [comment]
@googlebot I signed it!

**Comment by DartMen** [comment]
> Closing as CLA was not signed

I signed CLA, would you mind reopening this PR?

**Comment by DartMen** [comment]
@mit-mit please re-open PR?

**Comment by mit-mit** [comment]
@DartMen I tried to re-open this but 1) the CLA bot can't see that, and 2) there is a merge conflict. Can you open a new PR, pls?

**Pull request closed without merging**
