### PR TITLE
Merge http_retry into this package

### PR DESCRIPTION
**Pull request by natebosch**
Update all references to `http_retry` to `http/retry`. Shorten the
README content a bit and put it a separate section.

### CODE REVIEW

**Comment by natebosch** [comment]
These commits have already been accepted into a dart-lang repo. The CLA shouldn't be an issue for this merge.

**Review by kevmoo — APPROVED** [review]

**Comment by natebosch** [comment]
I'll need to temporarily enable merge commits to preserve history here.

Unfortunately I think we'll have a double merge, since the HEAD commit of this branch is already a merge. I think that's probably fine.

@kevmoo  do you have any concerns about that?

**Review by jakemac53 — APPROVED** [review]
Generally this LGTM, although it is a bit unfortunate to have the separate library, I assume that is to avoid import conflicts?

**Comment by natebosch** [comment]
> I assume that is to avoid import conflicts?

Yes. If everyone is following the advice of using an import prefix for `http`, and is _not_ doing that for `http_retry` then in theory it should be safe, but I'm not confident that is the case.

I'm also not entirely sure it makes sense to have `RetryClient` in the general library for this package. It's a bit specialized IMO.

**Comment by jakemac53** [comment]
> I'm also not entirely sure it makes sense to have `RetryClient` in the general library for this package. It's a bit specialized IMO.

Ya it just isn't much code, andits likely very tree-shakeable code as well. Plus we don't typically do separate libraries. I don't think it is a big deal either way though so LGTM.

**Comment by EgHubs** [comment]
Sorry for referencing here, but since version 13.0, there been many errors that we all facing, please review them in the issue center
Mine here

https://github.com/dart-lang/http/issues/550

**Comment by natebosch** [comment]
We synced offline and decided to go forward with separate libraries, and also to merge this manually instead of through a github PR.

**Pull request closed without merging**
