### PR TITLE
Require Dart 2.14, prepare to release v0.13.4

### PR DESCRIPTION
**Pull request by kevmoo**
Removed unneeded utility function

### CODE REVIEW

**Review by jakemac53 — APPROVED** [review]
Has the other change here already been rolled internally etc?

**Comment by kevmoo** [comment]
> Has the other change here already been rolled internally etc?

🤷  – will look

**Comment by kevmoo** [comment]
@jakemac53 – has NOT! 

Need to bump the dependency in the SDK and roll it through.

I'll do that after I land this – and before we publish.

although I have zero clue why chrome is being weird...

**Comment by jakemac53** [comment]
> although I have zero clue why chrome is being weird...

Having issues on another pr of mine in package:build as well. This is a consistent issue with github actions unfortunately....

**Pull request merged**
