### PR TITLE
Merge 0.11.x fixes to master

### PR DESCRIPTION
**Pull request by yjbanov**

### CODE REVIEW

**Comment by donny-dont** [comment]
@nex3 can you cherry pick everything but #59 for this and apply to master?

**Comment by yjbanov** [comment]
There's also https://github.com/dart-lang/http/commit/f5adb791f390f474d815ba08c4449fc124184b9a that could bite some people that we might want to pull into master. Maybe it's better to close this PR and create a fresh one.

**Comment by donny-dont** [comment]
Yea whatever you think @yjbanov . After this batch of PRs land then figuring out what to about multiparts so it would be good to get any changes around that into master

**Comment by yjbanov** [comment]
Cool. Closing then. Feel free to pick up the task of merging to `master`.

**Pull request closed without merging**
